### ISSUE TITLE
Bubbled face emoji appears as 2 separate emojis when you type

### ISSUE THREAD

**Issue by foxnoodles** [PoomSmart/EmojiPort-PS#3]
New iOS 15 emoji, 3rd from the top in first column on the keyboard shown on the screenshot bellow:
![IMG_0057](https://user-images.githubusercontent.com/1949828/152640730-9d7a7946-5b2b-4e6d-a1d0-8acf39df9e3e.PNG)

**Comment by PoomSmart** [comment]
Fixed in recent versions.
